# Generated by Django 5.1.1 on 2024-09-30 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TaskTitle', models.CharField(max_length=100)),
                ('TaskDescription', models.TextField()),
                ('is_completed', models.BooleanField(default=False)),
                ('TaskAssingDate', models.DateField(auto_now_add=True)),
                ('categories', models.ManyToManyField(to='category.category')),
            ],
        ),
    ]
